# .github/workflows/ci.yml
name: Smart Parking CI

on:
  push:
    branches: [ "master", "New_Module"]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Install xvfb for Tkinter Headless Testing
      run: sudo apt-get install -y xvfb

    - name: Run Unit Tests
      run: |
        pytest test/test.py -v
